name: Configure CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  configure:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        compiler: [cl, clang-cl]
        build_type: [debug, release]
    runs-on: ${{ matrix.os }}

    env:
      preset: ${{matrix.compiler}}-${{matrix.arch}}-${{matrix.build_type}}
      output_dir: ${{github.workspace}}/out/build/${{matrix.compiler}}-${{matrix.arch}}-${{matrix.build_type}}
      shared_dependency_cache: ${{matrix.os}}-${{matrix.arch}}

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{matrix.arch}}
        
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/out/build/${{env.preset}}/vcpkg_installed
        key: ${{env.shared_dependency_cache}}-${{hashFiles('**/vcpkg.json')}}
        enableCrossOsArchive: true
    
    - name: Cache CMake Configuration
      id: cache-cmake-conf
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/out/build/${{env.preset}}
        key: ${{env.preset}}-${{hashFiles('**/CMakeLists.txt' '**/CMakePresets.json' '**/vcpkg.json')}}
        enableCrossOsArchive: true
    
    - name: Integrate vcpkg
      run: vcpkg integrate install

    - name: Configure CMake
      run: cmake --preset ${{env.preset}}